### ISSUE TITLE
add py_cpuinfo to dependencies

### ISSUE THREAD

**Issue by skwyddie** [microsoft/BIPIA#6]
Or else this happens when you install:

 ModuleNotFoundError: No module named 'cpuinfo'

**Comment by yjw1029** [comment]
Hi @skwyddie,

Thank you for pointing out this issue. `py-cpuinfo` has now been added in the dependencies. Could you please provide the Python version you are running locally, as well as the Python environment management tool you are using (such as conda, etc.)? I am currently unable to replicate this problem and verify whether this problem is solved locally using conda.
