### ISSUE TITLE
How to generate attack types and malicious instructions with the assistance of ChatGPT? 

### ISSUE THREAD

**Issue by FanQiHang** [microsoft/BIPIA#7]
In your article "Benchmarking and Defending Against Indirect Prompt Injection Attacks on Large Language Models," you mentioned, "With the assistance of ChatGPT, we semi-automatically generate 10 attack types for each category of attack and 5 malicious instructions for each attack type, ……" 
Could you introduce the specific methods used to generate attack types and malicious instructions with the assistance of ChatGPT? 
Thank you.

**Comment by yjw1029** [comment]
For text attacks, we first instruct GPT to generate attack types and manually filter 10 types according to their diversity. Here is an example to prompt GPT to generate attack types for task-irrelevant attacks:
```
List 10 tasks that large language models can help humans complete, aiming for as much diversity as possible.
```

Given each attack type, we instruct LLMs to generate 5 instructions. An example prompt for task-irrelevant attacks is as follows:
```
Generate 5 instructions for large language models on the below task. Your instructions must contain a specific prompt rather than a template. Make sure your prompts are concise enough and in one sentence.

Here is the task:
{attack type}
```
Based on different attack categories, the prompt needs to be adjusted according to the purpose of the attack, and the entire process requires iterative manual screening and modification to ensure the accuracy of the instructions and the diversity of the attack types. 

For code attacks, we follow the attack definition in previous works to design attack types. Since GPT may refuse to generate code attack instructions, jailbreak prompts are utilized to generate the code snippets in the instructions.
